name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
  push:
    branches:
      - 'brian/workflow*'
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install GNU Arm Embedded Toolchain
        uses: ./.github/actions/aarch64-none-elf-gcc-action
        with:
          release: '11.3.rel1'
      - name: Print GCC enviroment
        run: |
          echo "CROSS_COMPILER_ROOT=" >> "$GITHUB_ENV"
          echo "CROSS_COMPILE=aarch64-none-elf-" >> "$GITHUB_ENV"
          aarch64-none-elf-gcc --version
          which aarch64-none-elf-gcc
          which aarch64-none-elf-cpp
          which aarch64-none-elf-as
          which aarch64-none-elf-ar
          which aarch64-none-elf-ld
          which aarch64-none-elf-nm
          which aarch64-none-elf-objcopy
          which aarch64-none-elf-objdump
          which aarch64-none-elf-readelf
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build repository
        run: |
          cd npcm8xx
          echo "Current directory: $(pwd)"
          make
      - run: echo "This job's status is ${{ job.status }}."
